"""Add roles, podcast stats, and live stream model

Revision ID: dbafb9ebff90
Revises: 263375d5ca16
Create Date: 2025-07-06 10:11:19.900209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbafb9ebff90'
down_revision: Union[str, Sequence[str], None] = '263375d5ca16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
