"""Further database schema updates

Revision ID: f617a6827301
Revises: 05d664020a87
Create Date: 2025-07-07 07:11:32.546700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f617a6827301'
down_revision: Union[str, Sequence[str], None] = '05d664020a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_viewers', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_streams_id'), 'live_streams', ['id'], unique=False)
    op.create_index(op.f('ix_live_streams_title'), 'live_streams', ['title'], unique=False)
    op.drop_table('livestream')
    op.add_column('podcasts', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('podcasts', sa.Column('plays', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'plays')
    op.drop_column('podcasts', 'views')
    op.create_table('livestream',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_live', sa.BOOLEAN(), nullable=False),
    sa.Column('stream_url', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_live_streams_title'), table_name='live_streams')
    op.drop_index(op.f('ix_live_streams_id'), table_name='live_streams')
    op.drop_table('live_streams')
    # ### end Alembic commands ###
